CREATE TABLE Users(
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    mobile VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(550) NOT NULL,
    shop_name VARCHAR(550) NOT NULL
)